title: Drone navigation sim
description: "Simulation of an aerial drone in 3 dimensions. Showcase of obstacle avoidance strategy using PD controller and potential field evasion technique."
tier: 1
image: ''
date: 2025-11-30